# Generated by Django 2.2.6 on 2019-10-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(default='default.jpg', upload_to='screenshots')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('design', models.IntegerField(blank=True, default=7.0)),
                ('usability', models.IntegerField(blank=True, default=7.0)),
                ('overall', models.IntegerField(blank=True, default=7.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
