# Generated by Django 2.2.6 on 2019-10-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20191021_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
        migrations.AlterField(
            model_name='project',
            name='overall',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='award.Project'),
        ),
    ]
