# Generated by Django 2.2.6 on 2019-10-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20191024_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='overall',
        ),
    ]
